# Use Debian bookwork armv8 as the base image
FROM arm64v8/debian:bookworm

COPY qemu-arm64-static /usr/bin


# Install essential tools and compilers for mpa104 and onboard
RUN apt-get update && apt-get install -y \
    wget  build-essential sudo python3-packaging python3-dev \
    dh-python python3-distutils-extra devscripts pkg-config \
    libgtk-3-dev libxtst-dev libxkbfile-dev libdconf-dev libcanberra-dev \
    libhunspell-dev libudev-dev \
    python3-all-dev python3-cairo debhelper sudo
    

WORKDIR /

ENTRYPOINT ["/usr/local/bin/build_debs.sh"]
